# Generated by Django 2.2.5 on 2019-09-10 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import links.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('linkset', djongo.models.fields.ArrayModelField(model_container=links.models.Link)),
                ('fileset', djongo.models.fields.ArrayModelField(model_container=links.models.FileObject)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
