# Generated by Django 2.2.5 on 2019-09-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_fileobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileobject',
            name='name',
            field=models.CharField(default='NameLess', max_length=9999),
        ),
    ]
