# Generated by Django 2.2.5 on 2019-09-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_fileobject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileobject',
            name='suffix',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='link',
            name='is_fileobject',
            field=models.BooleanField(default=False),
        ),
    ]
